// 20170920155053
// https://api.myjson.com/bins/12jjwd

{
  "Laptop": [
    {
      "img0": "https://image.ibb.co/m9qNtk/Apple_model_1.jpg",
      "img1": "https://image.ibb.co/daZbKQ/Apple_model_1.jpg",
      "img2": "https://image.ibb.co/daZbKQ/Apple_model_1.jpg",
      "img3": "https://image.ibb.co/daZbKQ/Apple_model_1.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "Apple-MODEL-1",
      "model": "one",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "white",
      "Company": "Apple",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/cPMRm5/Apple_model_05.jpg",
      "img1": "https://image.ibb.co/gkGbm5/Apple_model_02.jpg",
      "img2": "https://image.ibb.co/gkGbm5/Apple_model_02.jpg",
      "img3": "https://image.ibb.co/gkGbm5/Apple_model_02.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "Apple-MODEL-2",
 "model": "two",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "Black",
      "Company": "Apple",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/j9hctk/Apple_model_2.jpg",
      "img1": "https://image.ibb.co/jqddzQ/Apple_model_2.jpg",
      "img2": "https://image.ibb.co/jqddzQ/Apple_model_2.jpg",
      "img3": "https://image.ibb.co/jqddzQ/Apple_model_2.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "Apple-MODEL-03",
 "model": "three",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "white",
      "Company": "Apple",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/nFtveQ/Apple_model_03.jpg",
      "img1": "https://image.ibb.co/cAZ7tk/Apple_model_03.jpg",
      "img2": "https://image.ibb.co/cAZ7tk/Apple_model_03.jpg",
      "img3": "https://image.ibb.co/cAZ7tk/Apple_model_03.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "Apple-MODEL-4",
 "model": "four",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "White",
      "Company": "Apple",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/k58qeQ/Apple_model_07.jpg",
      "img1": "https://image.ibb.co/neFveQ/Apple_model_04.jpg",
      "img2": "https://image.ibb.co/neFveQ/Apple_model_04.jpg",
      "img3": "https://image.ibb.co/neFveQ/Apple_model_04.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "Apple-MODEL-5",
      "Ram": "4 GB RaM",
 "model": "five",
      "storage": "1 TB Storage",
      "color": "Black",
      "Company": "Apple",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/eTEwKQ/Aple_model_02.jpg",
      "img1": "https://image.ibb.co/cUZtYk/Apple_model_05.jpg",
      "img2": "https://image.ibb.co/cUZtYk/Apple_model_05.jpg",
      "img3": "https://image.ibb.co/cUZtYk/Apple_model_05.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "Apple-MODEL-6",
 "model": "six",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "Black",
      "Company": "Apple",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/k58qeQ/Apple_model_07.jpg",
      "img1": "https://image.ibb.co/gHysR5/Apple_model_06.jpg",
      "img2": "https://image.ibb.co/gHysR5/Apple_model_06.jpg",
      "img3": "https://image.ibb.co/gHysR5/Apple_model_06.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "Apple-MODEL-7",
      "Ram": "4 GB RaM",
 "model": "seven",
      "storage": "1 TB Storage",
      "color": "Black",
      "Company": "Apple",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/k58qeQ/Apple_model_07.jpg",
      "img1": "https://image.ibb.co/dDBbKQ/Apple_model_07.jpg",
      "img2": "https://image.ibb.co/dDBbKQ/Apple_model_07.jpg",
      "img3": "https://image.ibb.co/dDBbKQ/Apple_model_07.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "Apple-MODEL-8",
 "model": "eight",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "White",
      "Company": "Apple",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/dUXizQ/Apple_model_08.jpg",
      "img1": "https://image.ibb.co/hnqWm5/Apple_model_08.jpg",
      "img2": "https://image.ibb.co/hnqWm5/Apple_model_08.jpg",
      "img3": "https://image.ibb.co/hnqWm5/Apple_model_08.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "Apple-MODEL-9",
 "model": "nine",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "White",
      "Company": "Apple",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/c3iOzQ/Apple_model_09.jpg",
      "img1": "https://image.ibb.co/hqwAeQ/Apple_model_09.jpg",
      "img2": "https://image.ibb.co/hqwAeQ/Apple_model_09.jpg",
      "img3": "https://image.ibb.co/hqwAeQ/Apple_model_09.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "Apple-MODEL-10",
      "Ram": "4 GB RaM",
 "model": "ten",
      "storage": "1 TB Storage",
      "color": "White",
      "Company": "Apple",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/dKCrKQ/Apple_model_10.jpg",
      "img1": "https://image.ibb.co/cNRhtk/Apple_model_10.jpg",
      "img2": "https://image.ibb.co/cNRhtk/Apple_model_10.jpg",
      "img3": "https://image.ibb.co/cNRhtk/Apple_model_10.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "Apple-MODEL-11",
 "model": "leven",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "White",
      "Company": "Apple",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/b6F0Dk/HP_model_12.jpg",
      "img1": "https://image.ibb.co/eT8HR5/HP_model_12.jpg",
      "img2": "https://image.ibb.co/eT8HR5/HP_model_12.jpg",
      "img3": "https://image.ibb.co/eT8HR5/HP_model_12.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "Apple-MODEL-12",
 "model": "twelve",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "White",
      "Company": "Apple",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/eNUctk/hp_15_ac182nia.jpg",
      "img1": "https://image.ibb.co/gFPwKQ/hp_15_ac182nia.jpg",
      "img2": "https://image.ibb.co/gFPwKQ/hp_15_ac182nia.jpg",
      "img3": "https://image.ibb.co/gFPwKQ/hp_15_ac182nia.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "HP-MODEL-15ac182",
 "model": "thirteen",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "Black",
      "Company": "HP",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/b6F0Dk/HP_model_12.jpg",
      "img1": "https://image.ibb.co/eT8HR5/HP_model_12.jpg",
      "img2": "https://image.ibb.co/eT8HR5/HP_model_12.jpg",
      "img3": "https://image.ibb.co/eT8HR5/HP_model_12.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "HP-MODEL-12",
 "model": "fourteen",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "Black",
      "Company": "HP",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/chN8zQ/hp15_ay011nr.jpg",
      "img1": "https://image.ibb.co/jtbtzQ/hp15_ay011nr.jpg",
      "img2": "https://image.ibb.co/jtbtzQ/hp15_ay011nr.jpg",
      "img3": "https://image.ibb.co/jtbtzQ/hp15_ay011nr.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "HP-MODEL-hp15_ay011nr",
 "model": "fifteen",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "Black",
      "Company": "HP",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/iDMwm5/HP_15_r230nr.png",
      "img1": "https://image.ibb.co/iLCxtk/HP_15_r230nr.png",
      "img2": "https://image.ibb.co/iLCxtk/HP_15_r230nr.png",
      "img3": "https://image.ibb.co/iLCxtk/HP_15_r230nr.png",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "HP_15_r230nr",
 "model": "sixteen",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "Black",
      "Company": "HP",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/ePLBKQ/HP_model_02.jpg",
      "img1": "https://image.ibb.co/bCeStk/HP_model_02.jpg",
      "img2": "https://image.ibb.co/bCeStk/HP_model_02.jpg",
      "img3": "https://image.ibb.co/bCeStk/HP_model_02.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "HP_model_02",
 "model": "seventeen",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "Black",
      "Company": "HP",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/cbfp65/HP_model_03.jpg",
      "img1": "https://image.ibb.co/nssQeQ/HP_model_03.jpg",
      "img2": "https://image.ibb.co/nssQeQ/HP_model_03.jpg",
      "img3": "https://image.ibb.co/nssQeQ/HP_model_03.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "HP_model_03",
 "model": "eighteen",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "RED",
      "Company": "HP",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/h2DsR5/HP_model_04.jpg",
      "img1": "https://image.ibb.co/iKv6m5/HP_model_04.jpg",
      "img2": "https://image.ibb.co/iKv6m5/HP_model_04.jpg",
      "img3": "https://image.ibb.co/iKv6m5/HP_model_04.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "HP_model_04",
 "model": "ninteen",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "BLACK",
      "Company": "HP",
      "screen": "800*800",
      "Price": "200 Euro"
    },
    {
      "img0": "https://image.ibb.co/jB9z65/HP_model_06.jpg",
      "img1": "https://image.ibb.co/m3Rwm5/HP_model_06.jpg",
      "img2": "https://image.ibb.co/m3Rwm5/HP_model_06.jpg",
      "img3": "https://image.ibb.co/m3Rwm5/HP_model_06.jpg",
      "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae malesuada lectus. Cras hendrerit ligula sit amet nisl dapibus, eu ullamcorper neque lacinia. Cras hendrerit sit amet ex a porta. Mauris nisl velit, suscipit vitae velit at, rutrum condimentum nibh. Sed sit amet cursus massa, a interdum erat. Vivamus eleifend eleifend tellus nec commodo. Donec tristique metus eget augue malesuada, ut finibus augue gravida. Integer consequat venenatis gravida. Pellentesque sit amet velit ultricies, consequat nulla vel, fringilla massa. Nullam mollis auctor sapien luctus tristique. Maecenas tristique dolor eu ligula aliquam molestie. Morbi aliquam quis magna vitae feugiat. Maecenas elit urna, tristique non dapibus at, fringilla sit amet est. Vestibulum ultricies augue eu sodales pellentesque. Suspendisse auctor nulla finibus eleifend dictum. Nulla interdum dapibus urna vel ultricies.",
      "titulo": "HP_model_06",
 "model": "twenty",
      "Ram": "4 GB RaM",
      "storage": "1 TB Storage",
      "color": "BLACK",
      "Company": "HP",
      "screen": "800*800",
      "Price": "200 Euro"
    }
  ]
}
